import { DocsLayout } from "@/components/layout/DocsLayout";
import { PageNav } from "@/components/docs/PageNav";
import { CodeBlock } from "@/components/docs/CodeBlock";
import { Callout } from "@/components/docs/Callout";
import { PropertiesTable } from "@/components/docs/PropertiesTable";
import { ChevronRight } from "lucide-react";
import Link from "next/link";

const tocItems = [
  { id: "overview", title: "Overview" },
  { id: "list-records", title: "List Records" },
  { id: "create-record", title: "Create Record" },
  { id: "get-record", title: "Get Record" },
  { id: "update-record", title: "Update Record" },
  { id: "delete-record", title: "Delete Record" },
  { id: "type-binding", title: "Type-Aware Binding" },
  { id: "error-handling", title: "Error Handling" },
];

export default function DataManagementPage() {
  return (
    <DocsLayout>
      <div className="flex gap-16 min-h-screen">
        <div className="flex-1 max-w-3xl py-10 px-2 flex flex-col gap-12">

          {/* Breadcrumb */}
          <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
            <Link href="/" className="hover:text-foreground transition-colors">RootCX</Link>
            <ChevronRight className="w-3.5 h-3.5" />
            <Link href="/modules" className="hover:text-foreground transition-colors">Native Modules</Link>
            <ChevronRight className="w-3.5 h-3.5" />
            <span className="text-foreground">Data Management</span>
          </div>

          {/* Title */}
          <div className="flex flex-col gap-3">
            <h1 className="text-4xl font-bold tracking-tight">Data Management</h1>
            <p className="text-lg text-muted-foreground leading-7">
              Automatic CRUD REST API generated from your application manifest. Every entity declared in your
              manifest gets a fully functional, type-safe, ownership-aware HTTP API with zero additional configuration.
            </p>
          </div>

          {/* Overview */}
          <section className="flex flex-col gap-4" id="overview">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">Overview</h2>
            <p className="text-muted-foreground leading-7">
              When you define an entity in your RootCX manifest, the runtime automatically provisions a PostgreSQL
              table and exposes a complete set of CRUD endpoints for that entity. You do not write any controller
              code — the runtime introspects the manifest schema and generates type-aware SQL bindings, ownership
              enforcement, and validation at startup.
            </p>
            <p className="text-muted-foreground leading-7">
              Every request to a data endpoint is authenticated via the{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">Authorization: Bearer</code>{" "}
              header. The authenticated user's ID is extracted from the JWT and used to scope all read and write
              operations to records the user owns, unless an RBAC role grants broader access.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-2">Base URL Pattern</h3>
            <p className="text-muted-foreground leading-7">
              All data endpoints follow a consistent URL structure:
            </p>
            <CodeBlock language="text" code={`/api/v1/apps/{appId}/collections/{entity}`} />
            <p className="text-muted-foreground leading-7">
              Where <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">appId</code> is
              your application's unique identifier and{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">entity</code> is
              the snake_case name of your manifest entity (e.g.{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">posts</code>,{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">orders</code>,{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">product_reviews</code>).
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-2">System Fields</h3>
            <p className="text-muted-foreground leading-7">
              Every entity table automatically includes the following system-managed columns. These fields cannot
              be set by the client on create or update — the runtime enforces their values:
            </p>
            <PropertiesTable
              properties={[
                {
                  name: "id",
                  type: "TEXT",
                  description: "UUID v4, generated by the runtime on record creation. Globally unique.",
                },
                {
                  name: "owner_id",
                  type: "TEXT",
                  description: "The user ID extracted from the JWT of the authenticated user who created the record.",
                },
                {
                  name: "created_at",
                  type: "TIMESTAMPTZ",
                  description: "ISO 8601 timestamp set at insertion time. Never modified.",
                },
                {
                  name: "updated_at",
                  type: "TIMESTAMPTZ",
                  description: "ISO 8601 timestamp updated automatically on every PATCH request.",
                },
              ]}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Example Manifest Entity</h3>
            <CodeBlock
              language="yaml"
              code={`app:
  id: my-app
  name: My Application

entities:
  - name: posts
    fields:
      - name: title
        type: text
        required: true
      - name: body
        type: text
      - name: published
        type: boolean
        default: false
      - name: tags
        type: json
      - name: published_at
        type: date`}
            />
          </section>

          {/* List Records */}
          <section className="flex flex-col gap-4" id="list-records">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">List Records</h2>
            <p className="text-muted-foreground leading-7">
              Retrieves all records for the authenticated user within the specified entity collection. Results are
              ordered by <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">created_at DESC</code>{" "}
              so the most recently created records appear first.
            </p>

            <div className="rounded-lg border border-border bg-card p-4 flex flex-col gap-2">
              <div className="flex items-center gap-3">
                <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-400/10 rounded px-2 py-0.5">GET</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">
                  /api/v1/apps/{"{appId}"}/collections/{"{entity}"}
                </code>
              </div>
            </div>

            <h3 className="text-lg font-semibold text-foreground mt-2">Ownership Filtering</h3>
            <p className="text-muted-foreground leading-7">
              The list endpoint automatically filters results to records where{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">owner_id</code>{" "}
              matches the authenticated user's ID. Users cannot enumerate other users' records through this endpoint.
              If an RBAC policy grants the <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">admin</code> role,
              the ownership filter is bypassed and all records are returned.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-2">Response Format</h3>
            <CodeBlock
              language="json"
              code={`{
  "data": [
    {
      "id": "01926b3e-7c2d-7000-b1e2-3f4a5d6e7f8a",
      "owner_id": "01926b3e-1234-7000-aaaa-bbbbccccdddd",
      "title": "Hello World",
      "body": "My first post.",
      "published": false,
      "tags": null,
      "published_at": null,
      "created_at": "2025-01-15T10:30:00.000Z",
      "updated_at": "2025-01-15T10:30:00.000Z"
    }
  ],
  "count": 1
}`}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">curl Example</h3>
            <CodeBlock
              language="bash"
              code={`curl https://your-runtime.example.com/api/v1/apps/my-app/collections/posts \\
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..."`}
            />

            <Callout variant="info" title="Filtering and Pagination">
              The built-in list endpoint returns all owned records without cursor-based pagination or column
              filtering. For advanced querying — field filters, pagination, joins, or cross-user aggregations —
              expose a Worker as an RPC endpoint and run arbitrary SQL there.
            </Callout>
          </section>

          {/* Create Record */}
          <section className="flex flex-col gap-4" id="create-record">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">Create Record</h2>
            <p className="text-muted-foreground leading-7">
              Creates a new record in the entity collection. The runtime validates the request body against the
              manifest schema, injects all system fields, and persists the record. Returns the full created record
              with all system fields populated.
            </p>

            <div className="rounded-lg border border-border bg-card p-4 flex flex-col gap-2">
              <div className="flex items-center gap-3">
                <span className="text-xs font-mono font-bold text-blue-400 bg-blue-400/10 rounded px-2 py-0.5">POST</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">
                  /api/v1/apps/{"{appId}"}/collections/{"{entity}"}
                </code>
              </div>
            </div>

            <h3 className="text-lg font-semibold text-foreground mt-2">Request Body</h3>
            <p className="text-muted-foreground leading-7">
              Send a JSON object containing only the user-defined fields from the manifest. System fields (
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">id</code>,{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">owner_id</code>,{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">created_at</code>,{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">updated_at</code>)
              are silently ignored if included and always set by the runtime.
            </p>

            <PropertiesTable
              properties={[
                {
                  name: "title",
                  type: "string",
                  required: true,
                  description: "Required if the manifest field has required: true. A 400 is returned if absent.",
                },
                {
                  name: "body",
                  type: "string",
                  required: false,
                  description: "Optional text fields default to NULL unless a manifest default is defined.",
                },
                {
                  name: "published",
                  type: "boolean",
                  required: false,
                  description: "Boolean fields are bound as SQL BOOLEAN. Defaults to the manifest default value.",
                },
                {
                  name: "tags",
                  type: "object | array",
                  required: false,
                  description: "JSON fields accept any valid JSON value. Validated and stored as JSONB.",
                },
                {
                  name: "published_at",
                  type: "string (ISO 8601)",
                  required: false,
                  description: "Date/datetime fields are parsed and stored as TIMESTAMPTZ. Invalid dates return 400.",
                },
              ]}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Auto-Injected Fields</h3>
            <p className="text-muted-foreground leading-7">
              Before executing the INSERT, the runtime automatically adds:
            </p>
            <ul className="flex flex-col gap-1.5 text-muted-foreground text-sm leading-7 list-none pl-0">
              <li className="flex gap-2">
                <span className="text-muted-foreground/50 mt-0.5">—</span>
                <span><strong className="text-foreground font-medium">id</strong>: a new UUID v4 generated with <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">crypto.randomUUID()</code></span>
              </li>
              <li className="flex gap-2">
                <span className="text-muted-foreground/50 mt-0.5">—</span>
                <span><strong className="text-foreground font-medium">owner_id</strong>: the <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">userId</code> claim from the validated JWT</span>
              </li>
              <li className="flex gap-2">
                <span className="text-muted-foreground/50 mt-0.5">—</span>
                <span><strong className="text-foreground font-medium">created_at</strong> and <strong className="text-foreground font-medium">updated_at</strong>: current UTC timestamp at insertion time</span>
              </li>
            </ul>

            <h3 className="text-lg font-semibold text-foreground mt-2">curl Example</h3>
            <CodeBlock
              language="bash"
              code={`curl -X POST https://your-runtime.example.com/api/v1/apps/my-app/collections/posts \\
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "title": "Hello World",
    "body": "My first post content.",
    "published": false,
    "tags": ["intro", "welcome"]
  }'`}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Response — 201 Created</h3>
            <CodeBlock
              language="json"
              code={`{
  "data": {
    "id": "01926b3e-7c2d-7000-b1e2-3f4a5d6e7f8a",
    "owner_id": "01926b3e-1234-7000-aaaa-bbbbccccdddd",
    "title": "Hello World",
    "body": "My first post content.",
    "published": false,
    "tags": ["intro", "welcome"],
    "published_at": null,
    "created_at": "2025-01-15T10:30:00.000Z",
    "updated_at": "2025-01-15T10:30:00.000Z"
  }
}`}
            />
          </section>

          {/* Get Record */}
          <section className="flex flex-col gap-4" id="get-record">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">Get Record</h2>
            <p className="text-muted-foreground leading-7">
              Retrieves a single record by its ID. The runtime performs both an existence check and an ownership
              check in a single query. If the record does not exist or belongs to a different user, a{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">404 Not Found</code> is
              returned — the same response is used in both cases to prevent ID enumeration attacks.
            </p>

            <div className="rounded-lg border border-border bg-card p-4 flex flex-col gap-2">
              <div className="flex items-center gap-3">
                <span className="text-xs font-mono font-bold text-emerald-400 bg-emerald-400/10 rounded px-2 py-0.5">GET</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">
                  /api/v1/apps/{"{appId}"}/collections/{"{entity}"}/{"{id}"}
                </code>
              </div>
            </div>

            <h3 className="text-lg font-semibold text-foreground mt-2">Ownership Check</h3>
            <p className="text-muted-foreground leading-7">
              The SQL executed is equivalent to:
            </p>
            <CodeBlock
              language="sql"
              code={`SELECT * FROM posts
WHERE id = $1 AND owner_id = $2
LIMIT 1;`}
            />
            <p className="text-muted-foreground leading-7">
              This ensures that even if a client guesses a valid record ID, they cannot access another user's data.
              The ownership filter is removed for users with an admin-level RBAC role.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-2">curl Example</h3>
            <CodeBlock
              language="bash"
              code={`curl https://your-runtime.example.com/api/v1/apps/my-app/collections/posts/01926b3e-7c2d-7000-b1e2-3f4a5d6e7f8a \\
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..."`}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Response — 200 OK</h3>
            <CodeBlock
              language="json"
              code={`{
  "data": {
    "id": "01926b3e-7c2d-7000-b1e2-3f4a5d6e7f8a",
    "owner_id": "01926b3e-1234-7000-aaaa-bbbbccccdddd",
    "title": "Hello World",
    "body": "My first post content.",
    "published": false,
    "tags": ["intro", "welcome"],
    "published_at": null,
    "created_at": "2025-01-15T10:30:00.000Z",
    "updated_at": "2025-01-15T10:30:00.000Z"
  }
}`}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Response — 404 Not Found</h3>
            <CodeBlock
              language="json"
              code={`{
  "error": "record not found"
}`}
            />
          </section>

          {/* Update Record */}
          <section className="flex flex-col gap-4" id="update-record">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">Update Record</h2>
            <p className="text-muted-foreground leading-7">
              Partially updates an existing record. Only the fields present in the request body are modified —
              omitted fields retain their current values. This is a true partial update, not a full replacement.
            </p>

            <div className="rounded-lg border border-border bg-card p-4 flex flex-col gap-2">
              <div className="flex items-center gap-3">
                <span className="text-xs font-mono font-bold text-yellow-400 bg-yellow-400/10 rounded px-2 py-0.5">PATCH</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">
                  /api/v1/apps/{"{appId}"}/collections/{"{entity}"}/{"{id}"}
                </code>
              </div>
            </div>

            <h3 className="text-lg font-semibold text-foreground mt-2">Immutable Fields</h3>
            <p className="text-muted-foreground leading-7">
              The following fields are always stripped from the update payload before the SQL is constructed.
              Attempting to set them has no effect:
            </p>
            <ul className="flex flex-col gap-1.5 text-muted-foreground text-sm leading-7 list-none pl-0">
              <li className="flex gap-2">
                <span className="text-muted-foreground/50 mt-0.5">—</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">id</code>
                <span>— record identity is immutable once assigned</span>
              </li>
              <li className="flex gap-2">
                <span className="text-muted-foreground/50 mt-0.5">—</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">created_at</code>
                <span>— original creation timestamp is preserved</span>
              </li>
              <li className="flex gap-2">
                <span className="text-muted-foreground/50 mt-0.5">—</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">owner_id</code>
                <span>— ownership cannot be transferred via the API</span>
              </li>
            </ul>

            <h3 className="text-lg font-semibold text-foreground mt-2">Auto-Updated Fields</h3>
            <p className="text-muted-foreground leading-7">
              The <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">updated_at</code> column
              is always set to the current UTC timestamp, regardless of whether you include it in the body.
            </p>

            <h3 className="text-lg font-semibold text-foreground mt-2">curl Example</h3>
            <CodeBlock
              language="bash"
              code={`curl -X PATCH https://your-runtime.example.com/api/v1/apps/my-app/collections/posts/01926b3e-7c2d-7000-b1e2-3f4a5d6e7f8a \\
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "published": true,
    "published_at": "2025-01-15T12:00:00.000Z"
  }'`}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Response — 200 OK</h3>
            <CodeBlock
              language="json"
              code={`{
  "data": {
    "id": "01926b3e-7c2d-7000-b1e2-3f4a5d6e7f8a",
    "owner_id": "01926b3e-1234-7000-aaaa-bbbbccccdddd",
    "title": "Hello World",
    "body": "My first post content.",
    "published": true,
    "tags": ["intro", "welcome"],
    "published_at": "2025-01-15T12:00:00.000Z",
    "created_at": "2025-01-15T10:30:00.000Z",
    "updated_at": "2025-01-15T12:05:32.871Z"
  }
}`}
            />

            <Callout variant="warning" title="Empty Update Body">
              If you send a PATCH with an empty body or a body containing only immutable fields, the runtime
              will still execute an update that sets <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">updated_at</code>.
              Validate your payload client-side if you want to avoid no-op updates.
            </Callout>
          </section>

          {/* Delete Record */}
          <section className="flex flex-col gap-4" id="delete-record">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">Delete Record</h2>
            <p className="text-muted-foreground leading-7">
              Permanently deletes a record. The runtime verifies ownership before deletion. On success, a{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">204 No Content</code> response
              is returned with an empty body. Deletion triggers any configured PostgreSQL audit log triggers
              before the row is removed.
            </p>

            <div className="rounded-lg border border-border bg-card p-4 flex flex-col gap-2">
              <div className="flex items-center gap-3">
                <span className="text-xs font-mono font-bold text-red-400 bg-red-400/10 rounded px-2 py-0.5">DELETE</span>
                <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">
                  /api/v1/apps/{"{appId}"}/collections/{"{entity}"}/{"{id}"}
                </code>
              </div>
            </div>

            <h3 className="text-lg font-semibold text-foreground mt-2">Ownership Check</h3>
            <p className="text-muted-foreground leading-7">
              The runtime executes a DELETE with both the record ID and the authenticated user's ID in the WHERE
              clause. If the record does not exist or is owned by another user, the DELETE affects 0 rows and
              a <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">404 Not Found</code> is
              returned.
            </p>
            <CodeBlock
              language="sql"
              code={`DELETE FROM posts
WHERE id = $1 AND owner_id = $2;`}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">curl Example</h3>
            <CodeBlock
              language="bash"
              code={`curl -X DELETE https://your-runtime.example.com/api/v1/apps/my-app/collections/posts/01926b3e-7c2d-7000-b1e2-3f4a5d6e7f8a \\
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiJ9..."`}
            />

            <p className="text-muted-foreground leading-7">
              A successful delete returns HTTP <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">204 No Content</code> with
              no response body.
            </p>

            <Callout variant="warning" title="Permanent Deletion">
              Records deleted via this endpoint are permanently removed from the entity table. The audit log
              will capture the deleted row's data in the <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">old_record</code> JSONB
              column if the Audit Logs module is enabled, but no soft-delete mechanism is built into the data module.
            </Callout>
          </section>

          {/* Type Binding */}
          <section className="flex flex-col gap-4" id="type-binding">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">Type-Aware Binding</h2>
            <p className="text-muted-foreground leading-7">
              The runtime parses each field's value from the JSON request body and converts it to the appropriate
              SQL type before binding parameters. This prevents type coercion bugs and ensures the database
              receives well-typed values.
            </p>

            <PropertiesTable
              properties={[
                {
                  name: "text",
                  type: "SQL TEXT",
                  description: "Bound as-is. Any JSON string value is accepted. Numbers and booleans sent as strings are stored as strings.",
                },
                {
                  name: "integer",
                  type: "SQL INTEGER",
                  description: "Parsed with parseInt(). Non-integer values return a 400 validation error.",
                },
                {
                  name: "float",
                  type: "SQL DOUBLE PRECISION",
                  description: "Parsed with parseFloat(). Non-numeric values return a 400 validation error.",
                },
                {
                  name: "boolean",
                  type: "SQL BOOLEAN",
                  description: "Accepts JSON true/false. String 'true'/'false' are not coerced — send actual JSON booleans.",
                },
                {
                  name: "date / datetime",
                  type: "SQL TIMESTAMPTZ",
                  description: "Parsed via new Date(value). Invalid date strings return a 400 validation error. Always stored in UTC.",
                },
                {
                  name: "json",
                  type: "SQL JSONB",
                  description: "Accepts any JSON-serializable value (object, array, string, number, null). Stored as JSONB. Invalid JSON returns 400.",
                },
                {
                  name: "array",
                  type: "SQL TEXT[]",
                  description: "JSON arrays of strings are stored as PostgreSQL TEXT[]. Mixed-type arrays are rejected.",
                },
              ]}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Required Field Validation</h3>
            <p className="text-muted-foreground leading-7">
              If a field is declared <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">required: true</code> in
              the manifest and is absent or <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">null</code> in
              the request body, the runtime returns a <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">400 Bad Request</code> before
              any database interaction occurs.
            </p>
            <CodeBlock
              language="json"
              code={`{
  "error": "validation failed",
  "details": {
    "field": "title",
    "message": "field is required"
  }
}`}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Unknown Fields</h3>
            <p className="text-muted-foreground leading-7">
              Fields present in the request body that are not declared in the manifest are silently ignored.
              They are never persisted and do not cause errors. This allows clients to send extra metadata
              without breaking requests.
            </p>
          </section>

          {/* Error Handling */}
          <section className="flex flex-col gap-4" id="error-handling">
            <h2 className="text-2xl font-semibold tracking-tight border-b border-border pb-3">Error Handling</h2>
            <p className="text-muted-foreground leading-7">
              All error responses share a consistent JSON envelope. The{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">error</code> field
              is always a human-readable string. An optional{" "}
              <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-foreground">details</code> object
              provides structured context for validation errors.
            </p>

            <PropertiesTable
              properties={[
                {
                  name: "400 Bad Request",
                  type: "Validation Error",
                  description: "A required field is missing, a field value cannot be coerced to its declared type, or the JSON body is malformed.",
                },
                {
                  name: "401 Unauthorized",
                  type: "Authentication Error",
                  description: "No Authorization header was provided, or the Bearer token is missing, expired, or cryptographically invalid.",
                },
                {
                  name: "403 Forbidden",
                  type: "Authorization Error",
                  description: "The token is valid but the user's RBAC role does not permit the requested operation on this entity.",
                },
                {
                  name: "404 Not Found",
                  type: "Not Found",
                  description: "The record does not exist, or exists but is owned by a different user. Both cases return identical 404 responses.",
                },
                {
                  name: "500 Internal Server Error",
                  type: "Server Error",
                  description: "An unexpected database or runtime error occurred. Details are logged server-side but not exposed in the response body.",
                },
              ]}
            />

            <h3 className="text-lg font-semibold text-foreground mt-2">Error Response Shape</h3>
            <CodeBlock
              language="json"
              code={`// 400 — validation failure
{
  "error": "validation failed",
  "details": {
    "field": "published_at",
    "message": "invalid date value: 'not-a-date'"
  }
}

// 401 — missing or expired token
{
  "error": "unauthorized"
}

// 403 — insufficient permissions
{
  "error": "forbidden"
}

// 404 — record not found or not owned
{
  "error": "record not found"
}

// 500 — internal error (details withheld)
{
  "error": "internal server error"
}`}
            />
          </section>

        </div>

        <PageNav href="/modules/data" />
      </div>
    </DocsLayout>
  );
}
