//! Database privileges for one approval. The caller owns the transaction and
//! must roll it back on any error; role DDL and grants are transactional too.
use std::collections::HashSet;

use rootcx_types::{ActionAuthority, AppManifest, DataOperation, EntityContract};
use sqlx::{Postgres, Transaction};
use uuid::Uuid;

use crate::RuntimeError;
use crate::manifest::quote_ident;

pub(super) fn role_name(id: Uuid) -> String {
    format!("rootcx_action_{}", id.simple())
}

pub(super) async fn create_role(
    tx: &mut Transaction<'_, Postgres>,
    id: Uuid,
    manifest: &AppManifest,
    authority: &ActionAuthority,
) -> Result<(), RuntimeError> {
    validate_fk_effects(tx, manifest, authority).await?;
    let role = quote_ident(&role_name(id));
    execute(
        tx,
        &format!(
            "CREATE ROLE {role} NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE \
             NOINHERIT NOREPLICATION NOBYPASSRLS"
        ),
    )
    .await?;
    execute(
        tx,
        &format!(
            "GRANT USAGE ON SCHEMA {}, rootcx_system TO {role}",
            quote_ident(&manifest.app_id),
        ),
    )
    .await?;

    for (entity, operations) in &authority.data {
        let contract = manifest
            .data_contract
            .iter()
            .find(|contract| contract.entity_name == *entity)
            .ok_or_else(|| invalid(format!("unknown local entity '{entity}'")))?;
        let table = format!("{}.{}", quote_ident(&manifest.app_id), quote_ident(entity));
        if operations.contains(&DataOperation::Read) && !operations.contains(&DataOperation::Update)
        {
            // PostgreSQL row locks need UPDATE on any column AND UPDATE USING.
            // The approved RLS policy must allow read authority in USING while
            // requiring explicit update authority in WITH CHECK. This ACL alone
            // neither permits mutations nor makes read-only row locking work.
            let primary_key: Option<String> = sqlx::query_scalar(
                "SELECT a.attname::text
                 FROM pg_catalog.pg_index i
                 JOIN pg_catalog.pg_attribute a
                   ON a.attrelid = i.indrelid AND a.attnum = i.indkey[0]
                 WHERE i.indrelid = pg_catalog.to_regclass($1) AND i.indisprimary
                   AND a.attnum > 0 AND NOT a.attisdropped",
            )
            .bind(&table)
            .fetch_optional(&mut **tx)
            .await
            .map_err(RuntimeError::Schema)?;
            let primary_key = primary_key.ok_or_else(|| {
                invalid(format!(
                    "'{entity}' needs a primary key for approved read row locks"
                ))
            })?;
            execute(
                tx,
                &format!(
                    "GRANT UPDATE ({}) ON TABLE {table} TO {role}",
                    quote_ident(&primary_key),
                ),
            )
            .await?;
        }
        for operation in operations {
            let privilege = match operation {
                DataOperation::Read => {
                    let Some(privilege) = read_privilege(tx, &table, contract).await? else {
                        continue;
                    };
                    privilege
                }
                DataOperation::Create => "INSERT".to_string(),
                DataOperation::Update => "UPDATE".to_string(),
                DataOperation::Delete => "DELETE".to_string(),
            };
            execute(tx, &format!("GRANT {privilege} ON TABLE {table} TO {role}")).await?;
        }
    }

    for gateway in [
        "check_access",
        "check_cross_app_access",
        "check_publication_access",
        "check_approved_action_access",
    ] {
        execute(
            tx,
            &format!(
                "GRANT EXECUTE ON FUNCTION rootcx_system.{}(text) TO {role}",
                quote_ident(gateway),
            ),
        )
        .await?;
    }
    // Exact prefixes, not LIKE patterns: app IDs can contain underscores.
    // Only the zero-argument resolver signatures generated by Core qualify.
    let resolvers: Vec<String> = sqlx::query_scalar(
        "SELECT p.proname::text
         FROM pg_catalog.pg_proc p
         JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'rootcx_system' AND p.pronargs = 0
           AND (pg_catalog.starts_with(p.proname::text, $1)
                OR pg_catalog.starts_with(p.proname::text, $2))
         ORDER BY p.proname",
    )
    .bind(format!("rootcx_own.{}.", manifest.app_id))
    .bind(format!("rootcx_shared.{}.", manifest.app_id))
    .fetch_all(&mut **tx)
    .await
    .map_err(RuntimeError::Schema)?;
    for resolver in resolvers {
        execute(
            tx,
            &format!(
                "GRANT EXECUTE ON FUNCTION rootcx_system.{}() TO {role}",
                quote_ident(&resolver),
            ),
        )
        .await?;
    }
    Ok(())
}

async fn read_privilege(
    tx: &mut Transaction<'_, Postgres>,
    table: &str,
    contract: &EntityContract,
) -> Result<Option<String>, RuntimeError> {
    let sensitive: HashSet<&str> = contract
        .fields
        .iter()
        .filter(|field| field.sensitive)
        .map(|field| field.name.as_str())
        .collect();
    if sensitive.is_empty() {
        return Ok(Some("SELECT".into()));
    }

    // Include actual system/legacy columns, using the same sensitive-column
    // boundary as ordinary app execution.
    let columns: Vec<String> = sqlx::query_scalar(
        "SELECT attname::text FROM pg_catalog.pg_attribute
         WHERE attrelid = pg_catalog.to_regclass($1)
           AND attnum > 0 AND NOT attisdropped ORDER BY attnum",
    )
    .bind(table)
    .fetch_all(&mut **tx)
    .await
    .map_err(RuntimeError::Schema)?;
    for field in &sensitive {
        if !columns.iter().any(|column| column.as_str() == *field) {
            return Err(invalid(format!(
                "sensitive column '{}.{field}' is missing",
                contract.entity_name,
            )));
        }
    }
    let readable: Vec<String> = columns
        .iter()
        .filter(|column| !sensitive.contains(column.as_str()))
        .map(|column| quote_ident(column))
        .collect();
    if readable.is_empty() {
        return Ok(None);
    }
    Ok(Some(format!("SELECT ({})", readable.join(", "))))
}

pub(super) async fn drop_role(
    tx: &mut Transaction<'_, Postgres>,
    id: Uuid,
) -> Result<(), sqlx::Error> {
    let name = role_name(id);
    let exists: bool =
        sqlx::query_scalar("SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = $1)")
            .bind(&name)
            .fetch_one(&mut **tx)
            .await?;
    let role = quote_ident(&name);
    if exists {
        sqlx::query(&format!("DROP OWNED BY {role}"))
            .execute(&mut **tx)
            .await?;
    }
    sqlx::query(&format!("DROP ROLE IF EXISTS {role}"))
        .execute(&mut **tx)
        .await?;
    Ok(())
}

#[derive(sqlx::FromRow)]
struct ForeignKey {
    name: String,
    parent: String,
    child_schema: String,
    child: String,
    on_delete: String,
    on_update: String,
}

/// Referential actions bypass the child table's ACL/RLS. Check their full
/// operation closure before granting anything, never silently widen authority.
async fn validate_fk_effects(
    tx: &mut Transaction<'_, Postgres>,
    manifest: &AppManifest,
    authority: &ActionAuthority,
) -> Result<(), RuntimeError> {
    let constraints: Vec<ForeignKey> = sqlx::query_as(
        "SELECT k.conname::text AS name, parent.relname::text AS parent,
                child_ns.nspname::text AS child_schema, child.relname::text AS child,
                k.confdeltype::text AS on_delete, k.confupdtype::text AS on_update
         FROM pg_catalog.pg_constraint k
         JOIN pg_catalog.pg_class parent ON parent.oid = k.confrelid
         JOIN pg_catalog.pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
         JOIN pg_catalog.pg_class child ON child.oid = k.conrelid
         JOIN pg_catalog.pg_namespace child_ns ON child_ns.oid = child.relnamespace
         WHERE k.contype = 'f' AND parent_ns.nspname = $1
         ORDER BY parent.relname, child_ns.nspname, child.relname, k.conname",
    )
    .bind(&manifest.app_id)
    .fetch_all(&mut **tx)
    .await
    .map_err(RuntimeError::Schema)?;
    let mut pending: Vec<(String, DataOperation)> = authority
        .data
        .iter()
        .flat_map(|(entity, operations)| {
            operations
                .iter()
                .filter(|op| matches!(op, DataOperation::Delete | DataOperation::Update))
                .map(move |op| (entity.clone(), *op))
        })
        .collect();
    let mut visited = HashSet::new();
    while let Some((entity, operation)) = pending.pop() {
        if !visited.insert((entity.clone(), operation.as_str())) {
            continue;
        }
        for fk in constraints.iter().filter(|fk| fk.parent == entity) {
            let action = match operation {
                DataOperation::Delete => fk.on_delete.as_str(),
                DataOperation::Update => fk.on_update.as_str(),
                _ => unreachable!("only delete and update have referential effects"),
            };
            let effect = match action {
                "a" | "r" => continue, // NO ACTION / RESTRICT do not write children.
                "c" => operation,      // CASCADE preserves DELETE versus UPDATE.
                "n" | "d" => DataOperation::Update, // SET NULL / SET DEFAULT.
                _ => {
                    return Err(invalid(format!(
                        "foreign key '{}' has unsupported referential action '{action}'",
                        fk.name,
                    )));
                }
            };
            if fk.child_schema != manifest.app_id {
                return Err(invalid(format!(
                    "'{entity}.{}' via foreign key '{}' would {} '{}.{}'; \
                     cross-app referential effects cannot be approved",
                    operation.as_str(),
                    fk.name,
                    effect.as_str(),
                    fk.child_schema,
                    fk.child,
                )));
            }
            if !authority
                .data
                .get(&fk.child)
                .is_some_and(|operations| operations.contains(&effect))
            {
                return Err(invalid(format!(
                    "'{entity}.{}' via foreign key '{}' requires explicit '{}.{}' authority",
                    operation.as_str(),
                    fk.name,
                    fk.child,
                    effect.as_str(),
                )));
            }
            pending.push((fk.child.clone(), effect));
        }
    }
    Ok(())
}

fn invalid(message: String) -> RuntimeError {
    RuntimeError::Invalid(format!("action authority: {message}"))
}

async fn execute(tx: &mut Transaction<'_, Postgres>, sql: &str) -> Result<(), RuntimeError> {
    sqlx::query(sql)
        .execute(&mut **tx)
        .await
        .map_err(RuntimeError::Schema)?;
    Ok(())
}
